language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
addons:
  apt_packages:
    - pandoc
install:
- pip install pipenv
- pipenv install --dev --system --ignore-pipfile
script:
- pytest
