language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install pipenv
- pipenv install --dev --system --ignore-pipfile
script:
- pytest
deploy:
  provider: pypi
  user: khalas
  password:
    secure: sQRH2CHq4INHmGhR/84ruJ/CI6bFXsXfPtD0g/p1ljiQ+TUfLTFo8UEL6xXb+eXA3dPAlTrpDD8Kgtfv1Ot5dsIDGWpFWXAW7r3iyvOKUTXWfvq5+pRDjPHrzA0wlakJoVUZI3wMNN2uFqQ3+UJIPYLpqPSfz841FSYvPIFmwtt63k/lx/uWc1z1GIcbgsMRhDxogL7sM0Uyw3iV61qxK39GjlP/qYXRtTrZBaPcjg1YeUKept96klV81BiSDp0Mhaakwuq12vhvVntpy+tJAPtFAPH7wqD0WdxD70PmmcXdzd61a5m7y6Pl/ePOx2Hc15s59m580qs+BQSAoUlpGIwrlisnTRbT/gqOpRQgbWpmS1Ci22ADpl5Q8fl1KLHfsTMGGvwoJVVBvmgJwHF02APmz7VXuqsjIA5/ea7X0imrsVElGU4FyI9LlLJW7PdzEpnhXcD3hguMTGpKdKcJnrxEb8Ht2VdNnljrAGAQEMGnu680uFyveNh4AtEWr4iD1PMCskMpzdj6pWRSkwP3ElPSuQZfPqtRFy5mcwTpe0SPMIHcsqHnUsVINt+jOV05QA5r376CoW9insDz/GsmT1WjG8bd4EiPe0yYL5qHRXJDj4mMl3K1fSzGZJDQpjQIpOwEK/taRIvoVghcdC3TEnYHCzuR6ozB9Ip85iqsSRY=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
